### ISSUE TITLE
Connect Metamask

### ISSUE THREAD

**Issue by kevingkday** [darkcodi/nft-faucet#4] opened 2022-07-09 23:26 UTC
If the site is already connected to Metamask, and then I visit the site again, I am still asked to connect to Metamask (even though I already am).  When I select "connect" again, I get caught in a loop, reloading the connect page again and again.

**Comment by darkcodi** [comment] 2022-07-11 20:26
Hi @kevingkday ,
I cannot reproduce this issue (neither in Firefox 102, nor in Chrome 103).
Would you kindly tell me more about it? What's your browser? What STR (steps to reproduce)? If it's possible, please record a video or gif.

**Comment by kevingkday** [comment] 2022-07-13 22:37
Here is a video of the event.  I am using Brave browser.  If Metamask is not yet connected to the site, it works fine.  But after Metamask has been connected, if I close the browser and go back to the site, then it still asks me to connect Metamask and when I do I get caught in the loop.  Unfortunately in the video the Metamask window is not showing up - where you see the mouse circling that is me showing that Metamask is connected.

https://user-images.githubusercontent.com/7671505/178848729-6cafb78c-813f-4fde-b516-7950d0683737.mp4

**Comment by darkcodi** [comment] 2022-08-02 21:57
Sorry for the late response.  

I managed to reproduce this bug only in the **Brave browser**. The issue is that sometimes `GetSelectedAddress` returns `null` instead of an actual address in Metamask. I don't know what's the root cause, but I guess it might be somehow related to Brave intercepting calls to Metamask in order to promote its own Brave Wallet. I am not a JS developer, so don't want to dive deeper. I just tried replacing a library that is used for Metamask interaction (via JS interop) + removed a null check for `Address` in the `IsReady` method, and seems that fixed the problem 😄 
  
Commits: 3ea131c2589e2a2e2c68da90173b997fc4c7868d and 6564e9ec9d62a85c1102c40ed6fadc56c438edd4
  
I'll close this issue, coz I am unable to reproduce it after these recent changes. If you still encounter this problem - feel free to reopen the issue.

**Closed as completed by darkcodi** 2022-08-02 21:57 UTC
